services:
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: 
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
  database:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: you
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: php-docker
    
volumes:
  mysqldata:
