services:
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: 
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}

  database:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: you
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: php-docker

  cache:
    image: redis:latest
    
volumes:
  mysqldata:
